name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule: # Run workflow automatically
    - cron: "0 * * * *" # Runs every hour, on the hour
jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sriram23/sriram23@main
        with:
          max_post_count: 10
          feed_list: "https://sriram23.hashnode.dev/rss.xml"
